CREATE TABLE supplement (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name           VARCHAR(120)  NOT NULL,
    description    VARCHAR(1000) NOT NULL,
    typical_dosage VARCHAR(255)  NOT NULL,
    category       VARCHAR(60)   NOT NULL,
    is_custom      BOOLEAN       NOT NULL DEFAULT FALSE
);

CREATE TABLE supplement_benefit (
    supplement_id BIGINT       NOT NULL,
    benefit       VARCHAR(255) NOT NULL,
    position      INT          NOT NULL,
    CONSTRAINT pk_supplement_benefit PRIMARY KEY (supplement_id, position),
    CONSTRAINT fk_benefit_supplement FOREIGN KEY (supplement_id)
        REFERENCES supplement (id) ON DELETE CASCADE
);

CREATE TABLE supplement_buy_link (
    supplement_id BIGINT       NOT NULL,
    store_name    VARCHAR(60)  NOT NULL,
    url           VARCHAR(500) NOT NULL,
    position      INT          NOT NULL,
    CONSTRAINT pk_supplement_buy_link PRIMARY KEY (supplement_id, position),
    CONSTRAINT fk_buy_link_supplement FOREIGN KEY (supplement_id)
        REFERENCES supplement (id) ON DELETE CASCADE
);

CREATE TABLE user_supplement (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    supplement_id BIGINT      NOT NULL,
    added_date    DATE        NOT NULL,
    active        BOOLEAN     NOT NULL DEFAULT TRUE,
    -- device_id / updated_at are Phase 2 cloud-sync seams, unused in Phase 1
    device_id     VARCHAR(64),
    updated_at    TIMESTAMP   NOT NULL,
    CONSTRAINT uq_user_supplement UNIQUE (supplement_id),
    CONSTRAINT fk_user_supplement_supplement FOREIGN KEY (supplement_id)
        REFERENCES supplement (id) ON DELETE CASCADE
);

CREATE TABLE intake_log (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_supplement_id BIGINT    NOT NULL,
    taken_at           TIMESTAMP NOT NULL,
    log_date           DATE      NOT NULL,
    -- device_id / updated_at are Phase 2 cloud-sync seams, unused in Phase 1
    device_id          VARCHAR(64),
    updated_at         TIMESTAMP NOT NULL,
    CONSTRAINT fk_intake_log_user_supplement FOREIGN KEY (user_supplement_id)
        REFERENCES user_supplement (id) ON DELETE CASCADE
);

CREATE INDEX idx_intake_log_date ON intake_log (log_date);
