-- Built-in supplement catalog (18 entries). Benefits are general, commonly cited
-- effects and are informational only, not medical advice.

INSERT INTO supplement (id, name, description, typical_dosage, category, is_custom) VALUES
(1,  'Vitamin D3',           'The ''sunshine vitamin'', commonly supplemented in months with little sun exposure.',                                              '1000-4000 IU daily, with a meal containing fat',            'Vitamin',            FALSE),
(2,  'Vitamin C',            'A water-soluble antioxidant vitamin found in fruits and vegetables.',                                                              '250-1000 mg daily',                                          'Vitamin',            FALSE),
(3,  'Vitamin B12',          'Essential vitamin mainly found in animal products; important for vegans and vegetarians.',                                         '250-1000 mcg daily (methylcobalamin or cyanocobalamin)',     'Vitamin',            FALSE),
(4,  'Omega-3 (Fish Oil)',   'EPA and DHA fatty acids, usually sourced from fish or algae oil.',                                                                 '1-2 g combined EPA+DHA daily, with food',                    'Fatty acid',         FALSE),
(5,  'Magnesium',            'An essential mineral involved in over 300 enzymatic reactions; glycinate and citrate forms are well absorbed.',                    '200-400 mg daily, often in the evening',                     'Mineral',            FALSE),
(6,  'Zinc',                 'A trace mineral important for immunity, skin, and hormone production.',                                                            '10-25 mg daily, with food',                                  'Mineral',            FALSE),
(7,  'Creatine Monohydrate', 'One of the most researched sports supplements, stored in muscle as phosphocreatine.',                                             '3-5 g daily, any time of day',                               'Performance',        FALSE),
(8,  'Whey Protein',         'Fast-digesting dairy protein used to hit daily protein targets.',                                                                  '20-40 g per serving, as needed to meet protein goals',       'Protein',            FALSE),
(9,  'Probiotics',           'Live beneficial bacteria, often Lactobacillus and Bifidobacterium strains.',                                                       '1-10 billion CFU daily, per product label',                  'Gut health',         FALSE),
(10, 'Ashwagandha',          'Adaptogenic herb from Ayurvedic tradition, typically standardized as KSM-66 or Sensoril.',                                        '300-600 mg daily of root extract',                           'Herbal / Adaptogen', FALSE),
(11, 'Melatonin',            'Hormone that regulates the sleep-wake cycle; used short-term for sleep onset and jet lag.',                                        '0.5-3 mg, 30-60 minutes before bed',                         'Sleep',              FALSE),
(12, 'Iron',                 'Essential mineral for oxygen transport; supplement only if intake or levels are low.',                                             '14-27 mg daily, ideally with vitamin C; check levels first', 'Mineral',            FALSE),
(13, 'Calcium',              'The most abundant mineral in the body, mostly stored in bones and teeth.',                                                         '500-1000 mg daily if dietary intake is low',                 'Mineral',            FALSE),
(14, 'Collagen Peptides',    'Hydrolyzed collagen protein, typically types I and III from bovine or marine sources.',                                            '5-15 g daily, mixes into drinks',                            'Protein',            FALSE),
(15, 'Curcumin (Turmeric)',  'Active compound in turmeric; usually paired with piperine or a lipid formula for absorption.',                                     '500-1000 mg daily with black pepper extract',                'Herbal',             FALSE),
(16, 'CoQ10',                'Coenzyme Q10, involved in cellular energy production; levels decline with age and statin use.',                                    '100-200 mg daily, with a fatty meal',                        'Antioxidant',        FALSE),
(17, 'Electrolytes',         'Sodium, potassium, and magnesium blend for hydration during sweat-heavy activity.',                                                '1 serving during/after intense exercise or heat',            'Hydration',          FALSE),
(18, 'Multivitamin',         'Broad-spectrum blend of vitamins and minerals as nutritional insurance.',                                                          '1 serving daily, with food',                                 'Vitamin',            FALSE);

INSERT INTO supplement_benefit (supplement_id, benefit, position) VALUES
(1,  'Supports bone health and calcium absorption', 0),
(1,  'Supports immune system function', 1),
(1,  'May improve mood, especially in winter', 2),
(2,  'Supports immune defense', 0),
(2,  'Antioxidant protection against free radicals', 1),
(2,  'Aids collagen production and iron absorption', 2),
(3,  'Supports energy metabolism and reduces fatigue', 0),
(3,  'Supports red blood cell formation', 1),
(3,  'Supports nerve function', 2),
(4,  'Supports heart and cardiovascular health', 0),
(4,  'Supports brain function and memory', 1),
(4,  'Helps reduce inflammation and supports joint health', 2),
(5,  'Supports muscle relaxation and recovery', 0),
(5,  'May improve sleep quality', 1),
(5,  'Supports nervous system and energy metabolism', 2),
(6,  'Supports immune function', 0),
(6,  'Supports skin health and wound healing', 1),
(6,  'Contributes to normal testosterone levels', 2),
(7,  'Increases strength and power output', 0),
(7,  'Supports muscle growth alongside training', 1),
(7,  'May support cognitive performance', 2),
(8,  'Supports muscle repair and growth', 0),
(8,  'Convenient way to increase daily protein intake', 1),
(8,  'Rich in essential amino acids (high leucine)', 2),
(9,  'Supports gut flora balance and digestion', 0),
(9,  'May reduce bloating and digestive discomfort', 1),
(9,  'Supports immune health via the gut', 2),
(10, 'May reduce stress and cortisol levels', 0),
(10, 'May improve sleep quality', 1),
(10, 'May support strength and recovery', 2),
(11, 'Helps fall asleep faster', 0),
(11, 'Useful for jet lag and shift work', 1),
(11, 'Supports regulation of circadian rhythm', 2),
(12, 'Supports red blood cell and hemoglobin production', 0),
(12, 'Helps reduce tiredness caused by low iron', 1),
(12, 'Important for menstruating people and endurance athletes', 2),
(13, 'Supports bone and teeth strength', 0),
(13, 'Supports muscle contraction and nerve signaling', 1),
(13, 'Works together with vitamin D3 and K2', 2),
(14, 'Supports skin elasticity and hydration', 0),
(14, 'Supports joint, tendon, and ligament health', 1),
(14, 'Supports hair and nail strength', 2),
(15, 'Helps reduce inflammation', 0),
(15, 'Supports joint comfort and mobility', 1),
(15, 'Antioxidant support', 2),
(16, 'Supports cellular energy production', 0),
(16, 'Supports heart health', 1),
(16, 'Antioxidant protection', 2),
(17, 'Supports hydration and fluid balance', 0),
(17, 'Helps prevent muscle cramps', 1),
(17, 'Replaces minerals lost through sweat', 2),
(18, 'Covers common micronutrient gaps in the diet', 0),
(18, 'Convenient all-in-one formula', 1),
(18, 'Supports overall health and energy', 2);

-- Templated search URLs, not hardcoded product links.
INSERT INTO supplement_buy_link (supplement_id, store_name, url, position) VALUES
(1,  'Amazon', 'https://www.amazon.com/s?k=vitamin+d3', 0),
(1,  'iHerb',  'https://www.iherb.com/search?kw=vitamin+d3', 1),
(1,  'eMAG',   'https://www.emag.ro/search/vitamina%20d3', 2),
(2,  'Amazon', 'https://www.amazon.com/s?k=vitamin+c', 0),
(2,  'iHerb',  'https://www.iherb.com/search?kw=vitamin+c', 1),
(2,  'eMAG',   'https://www.emag.ro/search/vitamina%20c', 2),
(3,  'Amazon', 'https://www.amazon.com/s?k=vitamin+b12', 0),
(3,  'iHerb',  'https://www.iherb.com/search?kw=vitamin+b12', 1),
(3,  'eMAG',   'https://www.emag.ro/search/vitamina%20b12', 2),
(4,  'Amazon', 'https://www.amazon.com/s?k=omega+3+fish+oil', 0),
(4,  'iHerb',  'https://www.iherb.com/search?kw=omega+3+fish+oil', 1),
(4,  'eMAG',   'https://www.emag.ro/search/omega%203', 2),
(5,  'Amazon', 'https://www.amazon.com/s?k=magnesium+glycinate', 0),
(5,  'iHerb',  'https://www.iherb.com/search?kw=magnesium+glycinate', 1),
(5,  'eMAG',   'https://www.emag.ro/search/magneziu', 2),
(6,  'Amazon', 'https://www.amazon.com/s?k=zinc+picolinate', 0),
(6,  'iHerb',  'https://www.iherb.com/search?kw=zinc+picolinate', 1),
(6,  'eMAG',   'https://www.emag.ro/search/zinc%20supliment', 2),
(7,  'Amazon', 'https://www.amazon.com/s?k=creatine+monohydrate', 0),
(7,  'iHerb',  'https://www.iherb.com/search?kw=creatine+monohydrate', 1),
(7,  'eMAG',   'https://www.emag.ro/search/creatina%20monohidrata', 2),
(8,  'Amazon', 'https://www.amazon.com/s?k=whey+protein', 0),
(8,  'iHerb',  'https://www.iherb.com/search?kw=whey+protein', 1),
(8,  'eMAG',   'https://www.emag.ro/search/proteina%20whey', 2),
(9,  'Amazon', 'https://www.amazon.com/s?k=probiotics', 0),
(9,  'iHerb',  'https://www.iherb.com/search?kw=probiotics', 1),
(9,  'eMAG',   'https://www.emag.ro/search/probiotice', 2),
(10, 'Amazon', 'https://www.amazon.com/s?k=ashwagandha', 0),
(10, 'iHerb',  'https://www.iherb.com/search?kw=ashwagandha', 1),
(10, 'eMAG',   'https://www.emag.ro/search/ashwagandha', 2),
(11, 'Amazon', 'https://www.amazon.com/s?k=melatonin', 0),
(11, 'iHerb',  'https://www.iherb.com/search?kw=melatonin', 1),
(11, 'eMAG',   'https://www.emag.ro/search/melatonina', 2),
(12, 'Amazon', 'https://www.amazon.com/s?k=iron+supplement', 0),
(12, 'iHerb',  'https://www.iherb.com/search?kw=iron+supplement', 1),
(12, 'eMAG',   'https://www.emag.ro/search/fier%20supliment', 2),
(13, 'Amazon', 'https://www.amazon.com/s?k=calcium+supplement', 0),
(13, 'iHerb',  'https://www.iherb.com/search?kw=calcium+supplement', 1),
(13, 'eMAG',   'https://www.emag.ro/search/calciu%20supliment', 2),
(14, 'Amazon', 'https://www.amazon.com/s?k=collagen+peptides', 0),
(14, 'iHerb',  'https://www.iherb.com/search?kw=collagen+peptides', 1),
(14, 'eMAG',   'https://www.emag.ro/search/colagen%20peptide', 2),
(15, 'Amazon', 'https://www.amazon.com/s?k=curcumin+turmeric', 0),
(15, 'iHerb',  'https://www.iherb.com/search?kw=curcumin+turmeric', 1),
(15, 'eMAG',   'https://www.emag.ro/search/curcumina', 2),
(16, 'Amazon', 'https://www.amazon.com/s?k=coq10', 0),
(16, 'iHerb',  'https://www.iherb.com/search?kw=coq10', 1),
(16, 'eMAG',   'https://www.emag.ro/search/coenzima%20q10', 2),
(17, 'Amazon', 'https://www.amazon.com/s?k=electrolytes+powder', 0),
(17, 'iHerb',  'https://www.iherb.com/search?kw=electrolytes+powder', 1),
(17, 'eMAG',   'https://www.emag.ro/search/electroliti', 2),
(18, 'Amazon', 'https://www.amazon.com/s?k=multivitamin', 0),
(18, 'iHerb',  'https://www.iherb.com/search?kw=multivitamin', 1),
(18, 'eMAG',   'https://www.emag.ro/search/multivitamine', 2);

-- Keep identity generation clear of the seeded ids.
ALTER TABLE supplement ALTER COLUMN id RESTART WITH 100;
